<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 *
 * Process the image with TinyPNG service.
 */
function tinypng_entity_presave(EntityInterface $entity) {
  $config = \Drupal::config('tinypng.settings');

  if ($entity->isNew() && $entity->getEntityTypeId() == 'file' && empty(file_validate_is_image($entity)) ) {
    $config = \Drupal::config('tinypng.settings');
    $api_key = $config->get('api_key');
    // Skip if no api key is set.
    if (empty($api_key)) {
      return;
    }
    // Compress image.
    $image_path = $entity->getFileUri();
    \Tinify\setKey($api_key);
    $dest = drupal_realpath($image_path);

    try {
      if ($config->get('integration_method') == 'download') {
        $origin = file_create_url($image_path);
        $res = \Tinify\fromUrl($origin, $dest);
      }
      else {
        $res = Tinify\fromFile($dest)->toFile($dest);
      }
    }
    catch (Exception $ex) {
      \Drupal::logger('tinypng')->error($ex->getMessage());
    }
  }
}
