<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_presave().
 *
 * Process the image with TinyPNG service.
 */
function tinypng_entity_presave(EntityInterface $entity) {
  // Handle only newly uploaded images.
  if (
    !$entity->isNew()
    || $entity->getEntityTypeId() != 'file'
    || !empty(file_validate_is_image($entity))
  ) {
    return;
  }

  /** @var \Drupal\file\Entity\File $entity */
  if (!tinypng_is_mime_supported($entity->getMimeType())) {
    return;
  }

  // Skip if no api key is set or OnUpload method is not enabled.
  $api_key = tinypng_api_key();
  $on_upload = tinypng_handle_on_upload();
  if (empty($api_key) || empty($on_upload)) {
    return;
  }

  /** @var \Drupal\tinypng\TinyPng $tinypng */
  $tinypng = \Drupal::service('tinypng.compress');

  // Compress image.
  $image_path = $entity->getFileUri();
  try {
    if (tinypng_on_upload_method() == 'download') {
      $tinypng->setFromUrl($image_path);
    }
    else {
      $tinypng->setFromFile($image_path);
    }

    $res = $tinypng->saveTo($image_path);
  }
  catch (Exception $ex) {
    \Drupal::logger('tinypng')->error($ex->getMessage());
  }
}

/**
 * Get TinyPNG API key.
 */
function tinypng_api_key() {
  $config = \Drupal::config('tinypng.settings');
  return $config->get('api_key');
}

/**
 * Check ImageAction mode is enabled.
 */
function tinypng_handle_with_image_actions() {
  $config = \Drupal::config('tinypng.settings');
  return (bool) $config->get('image_action');
}

/**
 * Check OnUpload mode is enabled.
 */
function tinypng_handle_on_upload() {
  $config = \Drupal::config('tinypng.settings');
  return (bool) $config->get('on_upload');
}

/**
 * Get OnUpload method.
 */
function tinypng_on_upload_method() {
  $config = \Drupal::config('tinypng.settings');
  return $config->get('upload_method');
}

/**
 * Check mime type is supported.
 */
function tinypng_is_mime_supported($mime) {
  $supported_types = [
    'image/png',
    'image/jpg',
    'image/jpeg',
  ];
  return in_array($mime, $supported_types);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tinypng_form_image_style_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (tinypng_api_key() && tinypng_handle_with_image_actions()) {
    return;
  }

  /** @var \Drupal\image\Form\ImageStyleEditForm $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\image\Entity\ImageStyle $image_style */
  $image_style = $form_object->getEntity();

  // Remove TinyPNG from selectable list.
  unset($form['effects']['new']['effect']['data']['new']['#options']['tinypng_tinypng']);

  // Mark TinyPNG effect as disabled.
  foreach ($image_style->getEffects() as $effect) {
    /** @var \Drupal\image\ImageEffectBase $effect */
    if ('tinypng_tinypng' != $effect->getPluginId()) {
      continue;
    }

    $key = $effect->getUuid();
    $label = $effect->label() . ' ' . t('(Disabled)');
    $form['effects'][$key]['effect']['data']['label']['#plain_text'] = $label;
  }
}
